# Generated by Django 5.2.1 on 2025-06-10 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='follows',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbed_to', to=settings.AUTH_USER_MODEL, verbose_name='Подписка'),
        ),
    ]
